name: sneepy
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+15

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # State Management
  flutter_mobx: ^2.0.6+5
  mobx: ^2.2.0

  # Network
  dio: ^5.1.2
  connectivity_plus: ^4.0.2

  # Database
  hive_flutter: ^1.1.0

  # Localization
  easy_localization: ^3.0.2

  # Json
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1

  # Google
  google_mobile_ads: ^3.0.0

  # Purchase
  purchases_flutter: ^5.6.2

  # Notification
  onesignal_flutter: ^3.5.1

  # Image
  image_picker: ^0.8.7+5
  cached_network_image: ^3.2.3
  image_cropper: ^4.0.1

  # Utitilities
  kartal: ^2.8.0
  device_info_plus: ^8.2.2
  intl: ^0.18.0
  font_awesome_flutter: ^10.4.0
  fluttertoast: ^8.2.2
  url_launcher: ^6.1.12
  showcaseview: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.3
  mobx_codegen: ^2.3.0
  hive_generator: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/images/
